### PR TITLE
Initial Release Notes for 1.19.0

### PR DESCRIPTION
**Pull request by MikeWillCook**

### CODE REVIEW

**Comment by joshdalton** [comment]
@MikeWillCook what do we mean by "Add option to delete Custom Responses on import"?  What would drive which Custom Responses are deleted?

**Comment by joshdalton** [comment]
> @MikeWillCook what do we mean by "Add option to delete Custom Responses on import"? What would drive which Custom Responses are deleted?

Enable automatic or manual listing of Leveraged Authorizations - **where is this listing, how is it used?**
Deleting all Elements will leave name in text mentions - **Is this specific to Risk Solution @mentions?  I think noting it is for Risk Solutions would bring additional clarity for readers**
Include associations to Risk Solutions in project export - **what would be examples of associates? were these previously in the risk solutions file or missing?**

**Review by devbytyler — APPROVED** [review]
Looks great to me as a first stab

**Review by devbytyler — APPROVED** [review]

**Comment by MikeWillCook** [comment]
> > @MikeWillCook what do we mean by "Add option to delete Custom Responses on import"? What would drive which Custom Responses are deleted?
> 
> Enable automatic or manual listing of Leveraged Authorizations - **where is this listing, how is it used?** Deleting all Elements will leave name in text mentions - **Is this specific to Risk Solution @mentions? I think noting it is for Risk Solutions would bring additional clarity for readers** Include associations to Risk Solutions in project export - **what would be examples of associates? were these previously in the risk solutions file or missing?**

Expanded explanations on these changes to be more user friendly. @joshdalton are they more readable?

**Comment by joshdalton** [comment]
Yes, I like these updates - Thanks, @MikeWillCook!

**Pull request merged**
